- hosts: all
  user: ubi-lab
  sudo: yes
  tasks:
    - name: install chainer
      pip: name=chainer

    - name: clone pyCuda repository
      git: repo=http://git.tiker.net/trees/pycuda.git dest=pycuda
      sudo: no

    - name: build pyCuda
      shell: python configure.py chdir=pycuda

    - name: install pyCuda
      shell: python setup.py install chdir=pycuda
      environment:
        PATH: "/usr/local/cuda/bin:{{ ansible_env.PATH }}"
