- hosts: all
  user: ubi-lab
  sudo: yes
  tasks:
    - name: install chainer
      pip: name=chainer

    - name: clone pyCuda repository
      git: repo=git@github.com:inducer/pycuda.git

    - name: build pyCuda
      command: python configure.py && python setup.py install

    - name: install pyCuda
      command: make install
